import React from 'react';
import PostLayout from '../../components/PostLayout';

function LucidHoverPost() {
  return (
    <PostLayout
      title="LucidHover: hovering a function shouldn't mean reading it in isolation"
      subtitle="A VS Code extension that explains code in the context of the whole repo, using a fully local LLM."
    >
      <p>
        VS Code's built-in hover already tells you a function's signature and its docstring, if it has one.
        What it can't tell you is the thing you actually want to know before you touch unfamiliar code: what
        role does this function play in the rest of the repo, who calls it, what does it call, and what
        breaks if you change it. <strong>LucidHover</strong> is a VS Code extension built to answer that —
        hover a function, and instead of a summary of the function body in isolation, you get an explanation
        grounded in how it actually fits into the codebase around it.
      </p>

      <h2>Why local, and why that constraint mattered</h2>
      <p>
        Explanations are generated by a local LLM through <a href="https://ollama.com" target="_blank" rel="noopener noreferrer">Ollama</a> and
        cached in a local SQLite database. No API keys, no cloud LLM providers, no telemetry — code never
        leaves the machine. That wasn't a compliance checkbox; it's the reason the tool can index and explain
        an entire codebase automatically in the background without either a per-call API bill or a privacy
        conversation with whoever owns the repo. It does mean the extension has to do more work itself to be
        useful, since a small local model (the default is <code>qwen2.5-coder:1.5b</code>) is nowhere near as
        capable out of the box as a frontier hosted model — most of the actual engineering is in the context
        LucidHover builds and caches around each function, not in the model call itself.
      </p>

      <h2>How it works</h2>
      <p>
        On first activation in a trusted workspace, a local Python sidecar process parses the codebase with
        tree-sitter, builds a call graph, and ranks functions by importance using PageRank over that graph.
        Background indexing starts immediately, but only the highest-importance functions get pre-generated
        by default — everything else is generated on demand, the first time you actually hover it, so nothing
        ever shows a blank tooltip. Every explanation is cached in SQLite, keyed on the function's content,
        its surrounding context, the model used, and the prompt version — so an edit anywhere in that chain
        regenerates exactly the rows that are now stale, and nothing else.
      </p>
      <p>
        Hovering an already-indexed function is a cache lookup — instant, never a live model call. That
        distinction (cache hit vs. one-off synchronous generation) is what makes the extension feel responsive
        despite running entirely on local, comparatively small models.
      </p>

      <h2>What it surfaces beyond the hover tooltip</h2>
      <ul>
        <li><strong>Blast radius</strong> — everything that transitively depends on a function, before you change it.</li>
        <li><strong>Execution trace</strong> — the function's primary call chain forward, with inline branches for alternate paths.</li>
        <li><strong>Cluster summary</strong> — a synthesized purpose paragraph over a function and its transitive callers, built from already-cached explanations.</li>
        <li><strong>Show Most Important Functions</strong> — a quick pick of the codebase's highest-ranked functions, for orienting yourself in an unfamiliar repo.</li>
        <li><strong>Automatic staleness tracking</strong> — edits and cross-file changes flag affected explanations as stale, so you know when what you're reading no longer matches the code.</li>
      </ul>

      <h2>Architecture, in one pass</h2>
      <p>
        A local Python sidecar parses the repo with tree-sitter, builds a call graph, ranks functions by
        importance, and generates structured explanations via the local Ollama model — cached in SQLite so
        the same work is never repeated for an unchanged function. JavaScript, TypeScript, and TSX work out
        of the box on VS Code's own built-in symbol support; Python support needs a Python language extension
        (like Pylance) installed and active, since Python has no equivalent built-in symbol resolution to hook
        into.
      </p>

      <h2>Where it stands</h2>
      <p>
        Published to the VS Code Marketplace under an Apache-2.0 license. Source is public at{' '}
        <a href="https://github.com/NoorElAlfi/lucidHover" target="_blank" rel="noopener noreferrer">github.com/NoorElAlfi/lucidHover</a>.
      </p>
    </PostLayout>
  );
}

export default LucidHoverPost;
